### ISSUE TITLE
Squish __ftsc_date field not used in rescanned mails 

### ISSUE THREAD

**Issue by streaps** [huskyproject/hpt#18]
Squish uses MS-DOS time for the `date_written` field, which only has a 2-second resolution (10:05:23 is stored as 10:05:22). For preserving the accurate date/time of the original message, Squish has also the `__ftsc_date` field, which is written by hpt for imported mails.

Problem:
If an echomail area is rescanned, hpt doesn't read the original date/time from `__ftsc_date`, but uses `date_written`. Around 50% of the rescanned and exported messages have a timestamp that is 1 second off (the original timestamp). This could cause problems in dupe detection for some tossers. 

Solution:
Read and use the `__ftsc_date` field, if it is not empty.

**Comment by zoomosis** [comment]
I forgot to verify this earlier, but Squish 1.11 did indeed use the __ftsc_date field (when present) when scanning areas.

Scan_To() in s_scan.c:

```c
  if (*msg->__ftsc_date)
    (void)strcpy(p, msg->__ftsc_date);
  else (void)sprintf(p, "%02d %s %02d  %02d:%02d:%02d",
                     msg->date_written.date.da ? msg->date_written.date.da : 1,
                     months_ab[msg->date_written.date.mo
                                 ? msg->date_written.date.mo-1
                                 : 0],
                     (msg->date_written.date.yr+80) % 100,
                     msg->date_written.time.hh,
                     msg->date_written.time.mm,
                     msg->date_written.time.ss << 1);
```

Via https://github.com/sdudley/maximus/blob/1cc413a28df645aeb7170ac7524a05abf501e6ab/squish/s_scan.c#L1313
