### ISSUE TITLE
Packet message with null date

### ISSUE THREAD

**Issue by shtirlic** [huskyproject/hpt#41]
Please see my comment on commit https://github.com/huskyproject/hpt/commit/42195142c17ab50344b4abc28cd6316e711d81ed#commitcomment-48179950

hpt/lnx 1.9.0-cur 2021-03-11
all projects required at HEAD  and built via this Dockerfile ( https://github.com/shtirlic/ftn-bundle/blob/main/Dockerfile)

```
sys : Linux af560894a3ef 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
database: JAM
editor: golded
```

all resulting netmail pkt can not be read by rntrack

heres is the result from my test point hpt:

![image](https://user-images.githubusercontent.com/74080/110958024-481d2980-835d-11eb-8cea-de45d48dd742.png)

**Comment by dukelsky** [comment]
Please pull smapi and rebuild it

**Comment by shtirlic** [comment]
Confirmed, everything looking good now, thank you.
